# Generated by Django 5.1 on 2024-08-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppQuiz', '0002_quiz_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='example_or_doc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
